"""create evidence table

Revision ID: cac6509d590d
Revises: 9a5a62cbbe69
Create Date: 2026-08-27 18:41:33.782457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac6509d590d'
down_revision: Union[str, None] = '9a5a62cbbe69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.Enum('interview_transcript', 'customer_document', 'config_export', 'other', name='evidence_type'), nullable=False),
    sa.Column('qdrant_document_id', sa.String(length=255), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.String(length=32), nullable=True),
    sa.Column('suggested_requirement_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['audit_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    # ### end Alembic commands ###
